paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      security:
        - bearerAuth: []
      responses:
        200:
          description: Lista de productos obtenidos correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la respuesta
                    example: success
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        500:
          description: Error interno del servidor.

    post:
      summary: Crear un nuevo producto
      tags:
        - Products
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/CreateProduct'
      responses:
        201:
          description: Producto creado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la respuesta
                    example: success
                  payload:
                    $ref: '#/components/schemas/Product'
        500:
          description: Error interno del servidor.

  /api/products/{pid}:
    get:
      summary: Obtener un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto a obtener
          schema:
            type: string
      responses:
        200:
          description: Producto obtenido correctamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: Producto no encontrado.
        500:
          description: Error interno del servidor.

    put:
      summary: Actualizar un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto a actualizar
          schema:
            type: string
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/UpdateProduct'
      responses:
        200:
          description: Producto actualizado exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: Producto no encontrado.
        500:
          description: Error interno del servidor.

    delete:
      summary: Eliminar un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto a eliminar
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        200:
          description: Producto eliminado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la respuesta
                    example: success
        404:
          description: Producto no encontrado.
        500:
          description: Error interno del servidor.

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID del producto
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        status:
          type: boolean
          description: Estado del producto
        category:
          type: string
          description: Categoría del producto
        thumbnails:
          type: array
          description: Lista de miniaturas del producto
          items:
            type: string
        code:
          type: string
          description: Código del producto
        stock:
          type: number
          description: Stock del producto
        owner:
          type: string
          description: Dueño del producto
      example:
        _id: 60f0a9c9e6b3c2b4b8a6b2a0
        title: Laptop
        description: Una laptop potente para juegos.
        price: 1200
        status: true
        category: Tecnología
        thumbnails: 
          - https://example.com/thumbnail1.jpg
          - https://example.com/thumbnail2.jpg
        code: LP1234
        stock: 10
        owner: admin

  requestBodies:
    CreateProduct:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: Título del producto
              description:
                type: string
                description: Descripción del producto
              price:
                type: number
                description: Precio del producto
              status:
                type: boolean
                description: Estado del producto
              category:
                type: string
                description: Categoría del producto
              thumbnails:
                type: array
                description: Lista de miniaturas del producto
                items:
                  type: string
              code:
                type: string
                description: Código del producto
              stock:
                type: number
                description: Stock del producto
            required:
              - title
              - description
              - price
              - status
              - category
              - code
              - stock
          example:
            title: Laptop
            description: Una laptop potente para juegos.
            price: 1200
            status: true
            category: Tecnología
            thumbnails: 
              - https://example.com/thumbnail1.jpg
              - https://example.com/thumbnail2.jpg
            code: LP1234
            stock: 10

    UpdateProduct:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: Título del producto
              description:
                type: string
                description: Descripción del producto
              price:
                type: number
                description: Precio del producto
              status:
                type: boolean
                description: Estado del producto
              category:
                type: string
                description: Categoría del producto
              thumbnails:
                type: array
                description: Lista de miniaturas del producto
                items:
                  type: string
              code:
                type: string
                description: Código del producto
              stock:
                type: number
                description: Stock del producto
            required:
              - title
              - description
              - price
              - status
              - category
              - code
              - stock
          example:
            title: Laptop actualizada
            description: Una laptop potente para juegos y trabajo.
            price: 1500
            status: true
            category: Tecnología
            thumbnails: 
              - https://example.com/thumbnail
